### PR TITLE
Add option of providing default settings

### PR DESCRIPTION
**Pull request by mikker**
If the file `~/.live-server.json` exists, use its' contents as default options.

eg. I never want live-server to open my browser so I have 

```json
{
  "open": false
}
```

in my `~/.live-server.json`.

### CODE REVIEW

**Comment by mikker** [comment]
This adds another dependency. It's a very small one but worth noticing.

**Comment by harrytruong** [comment]
Hey @mikker, I think your intention with this PR is great. A default config file called `.live-server.json` would be nice. What do you think of also defining `liveServerConfig` within `package.json`? Something like this:

```js
{

  // ... package.json metadata ...

  "liveServerConfig" : {
    "port": 8181,
    "open": false
    // and so on..
  }
}
```

This is consistent with `package.json` configs for `jshint` ("[jshintConfig](http://jshint.com/docs/cli/#specifying-linting-options)") and `jscs` ("[jscsConfig](http://jscs.info/overview.html#cli)").

I'm curious to know @tapio's opinion on this feature.

**Comment by tapio** [comment]
I'm a bit sad that there starts to be so many options that a configuration file is becoming useful enough to  implement. Anyway, probably the right way is something along the line jshint does in @harrytruong's link. A way to provide project-specific settings is needed in addition to global (per user), and if it's not much code, both the server root relative file and package.json can be supported. Regarding the global home directory file, is there something more portable than `process.env.HOME` we could use (no HOME on Windows AFAIK)?

**Comment by mikker** [comment]
I honestly don't know about `HOME` but a quick search got me this http://stackoverflow.com/a/9081436/291503

```js
function getUserHome() {
  return process.env[(process.platform == 'win32') ? 'USERPROFILE' : 'HOME'];
}
```

I'll add it right now but I can't confirm if it really does work on Win.

As for the many config files – I totally get what you mean. I use `live-server` a lot in all many different projects and many of them have no package.json. But I know that I almost always would prefer to open my browser by myself. Hence this PR.

**Comment by tapio** [comment]
If we have multiple places for the config (e.g. global home directory file, server root relative file, server root package.json), how should they interact? The linked jshint docs say it stops at the first sight of existing configuration file, but I'd imagine it might be useful to provided user-wide defaults (e.g. "port") in the home directory and project specific overwrites to other things (e.g. "open") that extend the global config. JSHint has "extends" field that can be used to include other files, but that seems a bit too much for us.

**Comment by mikker** [comment]
`system wide < project wide < command line args` IMO.

**Comment by tapio** [comment]
> system wide < project wide < command line args IMO.
Yes, but should project wide settings extend the system wide ones, or should the system wide config be ignored if project wide config exists (like jshint seems to be doing).

**Comment by mikker** [comment]
They should compliment each other. As in, if they all were objects then `Object.assign(default, global, project, args)`.

**Comment by mikker** [comment]
Perfect! Glad to help :+1:

**Pull request merged**
