### PR TITLE
new feature: functional testing

### PR DESCRIPTION
**Pull request by harrytruong**
This is a work-in-progress, but it's already safe to merge. 

To run: `npm install` (because of new `devDependencies`) and `npm test`.

---

PR Highlights:

+ https://github.com/tapio/live-server/commit/2db3408bbf1af6be107a19e7ed1c694288efd854 refactored file structure, based on [bower](https://github.com/bower/bower)

  + Since I refactored the file structure, I figured getting this PR merged asap would be better.

+ https://github.com/tapio/live-server/commit/e5373beee1d9d07f9328b04403b27898479c67c7 added meta editor settings: `.editorconfig`, `.jshintrc`, `.eslintrc`

  + This helps with tab vs spaces.  (FWIW, I'd prefer spaces, but whatever floats your :boat:)

+ https://github.com/tapio/live-server/commit/601e9d552ba69e07dfb4d3a524fd15e054c71691 added testing structure, based on [bower](https://github.com/bower/bower) and [express](https://github.com/strongloop/express)

  + We're ready for integrating with [Travis CI](http://travis-ci.org) and [Coveralls](https://coveralls.io/). Not sure if I should go ahead and look into setting up those services?

  + I added example scripts (runnable via `./examples/basic/index.js`) to showcase `live-server` features, but I didn't document them in `README.md`. These examples are also used for testing (idea borrowed from express).

  + @tapio's original `eslint` rules are already throwing warnings. Not sure if I should go ahead and make those code changes. I tried to keep this PR from changing existing code...

    + **Note**: I made one tiny tweak to [index.js#L211](https://github.com/tapio/live-server/blob/601e9d552ba69e07dfb4d3a524fd15e054c71691/lib/index.js#L211): `LiveServer.start()` now returns `server`.

  + There are plenty of test cases to add. If this PR is merged, feel free to start adding placeholders. See `test/cli.js` or `test/acceptance/basic` and indicate new pending tests with `xit()`.

### CODE REVIEW

**Comment by evanplaice** [comment]
Not to be a buzzkill but JSPM will most likely replace Bower once ES6 -- which includes a standardized client-side module loader -- is supported in all browsers.

If you want to enforce consistent style-checking you're better off including [Standard][1]/[SemiStandard][2] and adding it to the npm test script.

As for linting, extensions are available for all popular editors that do live linting on the code as you type. For example, in Sublime you can add SublimeLinter + SublimeLinter-jshint via Package Control.

IMHO, I'm not a fan of cluttering the root dir with configuration files. Better alternatives exist.

OTOH, adding testing is a great idea. Maybe that commit can be cherry-picked and implemented.

[1]: https://github.com/feross/standard
[2]: https://github.com/Flet/semistandard

**Comment by harrytruong** [comment]
@evanplaice The PR used these particular tools because I directly based it off of existing projects (I think bower and express). But I agree with the jspm part (I use it regularly and definitely see it as part of the future).    

Thanks for your comments -- I think I agree with most of your points (and @tapio 's original feedback). Your post just reminded me that this PR is still hanging out there. I've been out of touch for a while, and I've diverged too much from the origin repo. 

I'm going to try to clean it up and re-submit within the week, unless you'd like to take a stab at it, @evanplaice ?

**Comment by evanplaice** [comment]
@harrytruong Unfortunately, your copy of master is pretty far out of sync with master and -- as a result -- there are some conflicts. I'll attempt to clean things up.

**Comment by evanplaice** [comment]
@tapio With PR #67 merged. It's probably safe to delete this PR. Unless you want testing coverage detection and continuation integration added back in.

**Pull request closed without merging**
