### PR TITLE
Replace colors.js with chalk

### PR DESCRIPTION
**Pull request by akx**
This PR replaces the `colors.js` dependency (which is having certain issues, see https://github.com/Marak/colors.js/issues/285) with https://github.com/chalk/chalk.

I hope I found all of the coloring invocations.

### CODE REVIEW

**Review by Qix- — APPROVED** [review]

**Comment by SoCuul** [comment]
Unfortunately this would not work, because chalk is an ESM-only package now.

**Comment by Qix-** [comment]
Chalk 5 is. The PR uses chalk 4.

**Comment by akx** [comment]
@SoCuul I took care to use Chalk 4 here.

**Comment by akx** [comment]
I've moved on to using https://github.com/lomirus/live-server, so closing this as some spring cleaning of my open PRs.

**Pull request closed without merging**
