### PR TITLE
Proxy support

### LINKED ISSUE #36: Add a way to proxy some requests path
On some projects, it's useful to have the static files served by live-server and rest api calls be directed to a real server. This enable us to work with the static files on their own.  E.g. anything /api/ calls gets redirected to http://127.0.0.1:8181/ which will be technically a java ee server executed from Eclipse for example.

The reason this is useful because you don't want to work with the static files served by these as sometimes it takes 3 to 5x reload for you to get your updated javascript/css shown.

### PR DESCRIPTION
**Pull request by pavel**
* Added proxy support (closes #36)

### CODE REVIEW

**Comment by moshemal** [comment]
can the ROUTE be a regex or a only a specific url?

**Comment by pavel** [comment]
ROUTE is a string, and is intended to be a specific URL.
It is passed as a `route` argument for connect's [`app.use`](https://github.com/senchalabs/connect/blob/master/index.js#L59-L110) function.

**Comment by moshemal** [comment]
It would be nice if it could support something like: some/url/*/foo/* (all URLs with "some/url" at the beginning which contain "foo" as a grandchild of "some/url" )

**Comment by pavel** [comment]
Probably, but the scope of this pull request is basic: forwarding a set of sub URLs to another server URL.

**Comment by icyitscold** [comment]
Thanks guys, awesome PR! When do you think this will be published to npm?

**Pull request merged**
