### PR TITLE
in response to issue #82

### PR DESCRIPTION
**Pull request by rodrigopmatias**

### CODE REVIEW

**Comment by rodrigopmatias** [comment]
not complete

**Comment by tapio** [comment]
What was missing and are you planning to submit a more complete version?

**Comment by rodrigopmatias** [comment]
there are settings that can be made according to the specification, the tests still lacking. But I'm no idea how to put all the parts of the configuration as it would many arguments.

what do you think optional keyword use a json type configuration file, would be within the project ideology?

**Comment by rodrigopmatias** [comment]
Document of W3C

https://www.w3.org/TR/cors/#access-control-allow-credentials-response-header

**Comment by genu** [comment]
Any update on this? 

I'm currently default to a chrome extension that enables CORS. It would be nice if `live-server` can be configured to force CORS on the responses.

**Comment by genu** [comment]
What is blocking this from getting it pulled in?

**Comment by tapio** [comment]
More complete CORS support should now be in courtesy of @pavel in #109. Will update npm today.

**Pull request closed without merging**
