### PR TITLE
Speed improvement. Closes #137

### LINKED ISSUE #137: Can i speed up the browser refresh after saving the file?
Hi, thanks for this excellent program!

I am using it in VS Code with Firefox, and there is approximately a 3 second delay in me pressing ctrl-s in the editor and the webpage being updated. Is there any way to speed this up? Thanks.

### PR DESCRIPTION
**Pull request by pavel**
Closes #137
* [watchr](https://github.com/bevry/watchr) is replaced by [chokidar](https://github.com/paulmillr/chokidar). This change boosts responsiveness of `live-server` to file system changes.
* `--ignorePattern=RGXP` option removed, as `--ignore=PATH` now accepts [anymatch](https://github.com/es128/anymatch) rules, which makes `--ignorePattern=RGXP` option obsolete.

### CODE REVIEW

**Comment by Learn-Digital-Audio** [comment]
#137 please see my comment regarding problems i had after trying this patch.

**Comment by Learn-Digital-Audio** [comment]
This patch is fantastic, really speeds up workflow.

**Comment by tapio** [comment]
I wonder would it be a problem to preserve `ignorePattern` as a hidden/deprecated option for backwards compatibility?

**Comment by pavel** [comment]
I'll restore `ignorePattern` option and mark it as deprecated.

**Comment by pavel** [comment]
I've messed up my branch. I'll create another PR from a new branch. Sorry.

**Comment by pavel** [comment]
New PR created. See #148.

**Pull request closed without merging**
