### PR TITLE
Match the </body> tag without case sensitivity.

### LINKED ISSUE #103: case-sensitivity of </body> tag match
I was editing some very old HTML which used [upper case tags](http://www.w3.org/TR/html-markup/documents.html#case-insensitivity). Live-server didn't work because (I think) the function `file(filepath, stat)` is looking for a case-sensitive match in `injectCandidates`. Note however the function `inject(stream)` does do a case-insensitive regex replacement.

Would it be possible to fix this either by adding `</BODY>` to `injectCandidates` or by making `injectCandidates`  an array of case-insensitive regexes and setting `injectTag` to the actual text matched.

I think this only applies to the `body` tag in HTML; SVG is XML and therefore case sensitive, so `SVG` is not a valid tag.

### PR DESCRIPTION
**Pull request by peterhull90**
Proposed fix with test case. Fixes #103

### CODE REVIEW

**Comment by tapio** [comment]
Thanks. I'll merge soon, after I can do a test run with it.

**Comment by peterhull90** [comment]
As a side comment I wasn't able to run all the tests on Windows, but I think the relevant ones did run. I don't know what the source of the error is (see attached.)
[test-output.txt](https://github.com/tapio/live-server/files/187483/test-output.txt)

**Comment by peterhull90** [comment]
Thanks. I do now know why the tests don't run on Windows. Are you interested in a PR for that?

**Comment by tapio** [comment]
Sure.

**Pull request merged**
