### PR TITLE
Several improvements

### LINKED ISSUE #82: Add support for Access-Control-Allow-Origin

### LINKED ISSUE #108: Mounting files does not work
Sample project:

* package.json
```json
{
  "name": "live-server-mount-file",
  "version": "0.0.0",
  "scripts": {
    "start": "live-server --no-browser --mount=/hi:./hi.html --port=8080"
  },
  "devDependencies": {
    "live-server": "~0.9.2"
  }
}
```

* hi.html
```html
<!DOCTYPE html>
<html>
<body><h3>Hi!</h3></body>
</html>
```
Steps to reproduce:
1. `npm i`
2. `npm start`
3. Browse to `http://localhost:8080/hi`.

Expected: HTML page with "Hi!" text
Got: 404 "Cannot GET /hi"

### PR DESCRIPTION
**Pull request by pavel**
* Adds support for mounting files (closes #108)
* Adds missing dev dependencies (eslint, jshint)
* Adds CORS support (closes #82)

### CODE REVIEW

**Comment by tapio** [comment]
Thanks!

**Comment by pavel** [comment]
My pleasure.

**Comment by genu** [comment]
I'm still unable to use the `--cors` flag it seems. In Chrome requests still get blocked across origins. I have to resort to a chrome extension in order to force cors. I was hoping that `--cors` would eliminate the need for it, did I misunderstand the purpose of the `--cors` flag?

**Comment by pavel** [comment]
@genu Can you please share a sample of the code you're using? Also please post output of `npm ls` executed in the project's folder, you're having trouble with.

**Comment by pavel** [comment]
@genu Conversation moved to #113.

**Pull request merged**
