### PR TITLE
Added easier entry point config in cli

### PR DESCRIPTION
**Pull request by harindu95**
I have added easier entry point configuration through cli arg. 
ex :
 live-server main.html 
   is equal to
 live-server --entry-point=main.html

### CODE REVIEW

**Comment by tapio** [comment]
Thanks, but I think this would be somewhat confusing as .html files would work differently than everything else, and you'd also lose the ability to serve a single .html file at root.

**Comment by harindu95** [comment]
Can you clarify it? This was added as the last elseif so it won't conflict with other options. When I first used live_server i expected it to work this way. That's why added this change.

**Comment by tapio** [comment]
A path that's given to live-server without a named parameter is interpreted as the path to use as the server root (default if not given is the current working directory). Usually this is a path to a folder, e.g. `live-server /tmp` which would serve the temp directory at localhost:8080. While less common, it can also be a single file, e.g. `live-server somefile.zip` which can be useful if you just want to quickly share one file over the network.

Your patch would add a special case for .html files, which could be surprising especially since it would then also expose all the files in the current working directory contrary to what is the behavior with other file types.

**Comment by harindu95** [comment]
ok. I understand. Thanks

**Pull request closed without merging**
