### PR TITLE
Add SPA (Single Page Application) support via a new --spa flag

### PR DESCRIPTION
**Pull request by evanplaice**
I stumbled on this application through the [Angular2 - 5 minute Quickstart][1] guide and -- so far -- have been very impressed with how easy it is to use.

One of the challenges for newcomers to SPA development in Angular -- and SPA frameworks in general -- is figuring out how to setup a testing server that maps incoming server requests to client-side SPA routes.

The intent of this feature is to make setting up a SPA testing/development server as simple/easy as possible.

The typical approach is to setup basic backend server with a catch-all route that maps incoming requests to the SPA entry point (ie `/index.html`). To preserve the route, the path is truncated and the route is re-appended as a hash fragment.

*For example, a request to:*
 `/blog/post/interesting-thoughts`

*Will translated to:*
`/#/blog/posts/interesting-thoughts`.

That's exactly what this addition accomplishes. When `live-server` is launched with the `--spa` flag, it intercepts an incoming request, restructures it, and fires off a 302 redirect to the application entry point. 

*Note: A 302 response is chosen because it's non-cacheable by default.*

Technically, the SPA redirect should only fire on inbound requests. Once the SPA is loaded, all internal linking is handled by the SPA router.

*There's probably some room for improvement here:*

- the hash fragment will likely need to be changed
- making the hash fragment configurable would allow compatibility other existing SPA frameworks
- choosing a 'sane' default would minimize configuration for the common use case
- live-server lacks a testing framework so I haven't had a chance to verify that this doesn't break anything

I'm planning on reaching out to the Angular dev team to ask for their input. From what I've come across so far, their primary focus is on the client-side and server-side implementation details will be left to the users. I'd like to bridge that gap and offer a low-barrier solution for people to get started.

Input/feedback is welcome :+1:

[1]: https://angular.io/docs/js/latest/quickstart.html

### CODE REVIEW

**Comment by evanplaice** [comment]
@tapio I fixed the merge conflicts.

I tried to get a straight answer from the angular dev team but they don't want to deal with server-side stuff or routing in general. They've been on a death march toward the beta launch.

> the hash fragment will likely need to be changed

Looks like the Ember.js community uses `#/` as the fragment. I can't find anything on React because nobody seems to be using it to create server-less apps. I've been using `#/` for my own app and I think it will be a good choice for now unless somebody explicitly requests an alternative.

Would it be possible to get this feature merged in? It could be a huge help to those of us doing front-end SPA development.

**Comment by tapio** [comment]
While the patch is small and as such I'm not totally opposed to merging it, it does seem rather specific with narrow field of applicability. I'm wondering if this could be implemented a bit more generically, ideally simultaneously catering for #36.

For example, if live-server would have a parameter similar to `http-server`:

    -P or --proxy Proxies all requests which can't be resolved locally to the given url. e.g.: -P http://someurl.com

Would something like `live-server --proxy /#` be satisfying?

**Comment by evanplaice** [comment]
It may possibly work but it would be an pain to configure.

Consider a 'typical' SPA structure:
- /
  - /app - all application-related javascript
  - /images - images
  - /scripts - vendor and non-application javascript
  - /stylesheets - css stylesheets
  - /index.html - main entry point

Since the application routes are dynamic would need to proxy all incoming requests to `/`,

*Except:*
- images
- scripts
- stylesheets

There would need to be some means to flip the logic. Implicitly proxy **all** incoming requests *except* `[excludePaths]`. It would be possible to simplify the configuration by isolating the static files to a single directory but that's not always an option (ex customer owned/preexisting codebases).

-----

The intent of this feature is to make the setup as stupid-simple as possible. Extend the ease and simplicity that live-server provides for live-reload/browser-open to a new class of applications. Make it so, even a front-end dev with little/no server-side experience can get up-and-running on SPA development in seconds.

This is not exactly an uncommon problem:
- https://github.com/isaacs/github/issues/408
- https://www.npmjs.com/package/express-spa-router
- http://www.nickdobie.com/blog/hosting-angularjs-with-amazon-s3/

I can understand the desire to reduce feature bloat. The change isn't significant enough to justify the cost (ie maintenance) of forking and creating a new variant.

**Comment by layflags** [comment]
This is very specific to SPAs working hash-based, but what about SPAs using `pushState`? There is also some discussion regarding this issue with [http-server](https://github.com/indexzero/http-server/issues/80).

**Comment by vitorfranca** [comment]
Any news on this?

**Comment by tapio** [comment]
I'll probably merge this since multiple people have expressed interest and it's a small patch. A bit busy at the moment though, so maybe next week I make a new release with this and some other stuff.

**Comment by Krisa** [comment]
+1

**Comment by evanplaice** [comment]
@tapio Awesome. I'll be sure to dogfood it and help provide fixes/support of users come across any issues. Let me know if I need to make any additional edits/fixes prior to being merged.

**Comment by tapio** [comment]
Sorry it took this long, but finally merged to master. Will publish to npm today. If you're up to it, test cases would be appreciated.

**Comment by kentor** [comment]
Right now it's also redirecting something like `/js/app.js` to `/#/js/app.js` right? That seems to not work as intended for most spas

**Comment by evanplaice** [comment]
@kentor Thanks for the feedback, I'll look into adding a fix for this issue.

Just to clarify, if the path ends with a file extension it should *not* redirect?

**Comment by kentor** [comment]
Right

**Pull request merged**
