### PR TITLE
Find Free Port to listen automatically

### PR DESCRIPTION
**Pull request by oliverzy**
This one make live-server find free port to listen automatically via find-free-port module.

This is useful when port specified is already in use.

### CODE REVIEW

**Comment by MetaMemoryT** [comment]
:+1: good work, this should be merged

**Comment by geelen** [comment]
Just came here to do a PR which does exactly this. Can we get this :+1:ed?

**Comment by harrytruong** [comment]
@oliverzy I think this is a great feature, but I'm not sure your PR is the ideal solution. The `find-free-port` module is unnecessary, since `http.server` can already re-select a random free port on its own. 

See [server.listen](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback) from the node docs:

> ... **A port value of zero will assign a random port.**

An ideal PR would include something like:

```js
server.addListener('error', function (e) {
  if (e.code == 'EADDRINUSE') {
    console.log('Address in use, retrying with random port...');
    setTimeout(function () {
      server.close();
      server.listen(0, host);
    }, 1000);
  }
});
```

The final log message would then use the `listening` event:

```js
server.addListener('listening', function(e) {
	var address = server.address(),
		serveURL = 'http://' + address.address + ':' +  address.port;

	// Output
	if (logLevel >= 1) {
		console.log(("Serving \"%s\" at %s").green, root, serveURL);
	}

	// Launch browser
	if (openPath !== null)
		open(serveURL + openPath);
});
```

@tapio @MetaMemoryT @geelen @oliverzy 
Let me know what you guys think. A PR from me is incoming.

**Comment by tapio** [comment]
Thanks people for your input. Personally I've been inclined to think that if the port is in use, it's likely to be an error situation and should be fixed by either finding out and terminating the process that occupies the port or changing your live-server port to one you can always use. However, since several people have voiced their support for this and I can see that in most cases you don't actually care in what port it runs, I've merged @harrytruong's solution, which I liked better - always nice to not add a dependency (even if npm makes them easy to handle).

Previously, I had (unvoiced :( ) concerns that silently using another port might lead to unintentional problems where you e.g. have a forgotten live-server instance pointing somewhere, then start another one which uses a new port without warning, but you work on the assumption that it's on 8080 (perhaps some testing scripts or hard-coded testing URLs) and wonder what is wrong when things don't work as expected. I think the red warning message in Harry's PR fixes this adequately.

**Pull request closed without merging**
